version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 50
    groups:
      golangx:
        patterns:
          - "golang.org/x/*"
      googles:
        patterns:
          -  "google.golang.org/*"
      otel:
        patterns:
          -  "go.opentelemetry.io/*"
    allow:
      # Keep the experimental modules up-to-date
      - dependency-name: "github.com/grafana/xk6-*"
        dependency-type: "all"
      # golang/x
      - dependency-name: "golang.org/x/*"
        dependency-type: "all"
      # google's grpc and protobuf
      - dependency-name: "google.golang.org/*"
        dependency-type: "all"
      # miscellaneous
      - dependency-name: "github.com/PuerkitoBio/goquery"
      - dependency-name: "github.com/andybalholm/brotli"
      - dependency-name: "github.com/evanw/esbuild"
      - dependency-name: "github.com/gorilla/websocket"
      - dependency-name: "github.com/grafana/sobek"
      - dependency-name: "github.com/jhump/protoreflect"
      - dependency-name: "github.com/klauspost/compress"
      - dependency-name: "github.com/tidwall/gjson"
      - dependency-name: "github.com/chromedp/cdproto"
      - dependency-name: "github.com/mailru/easyjson"
      - dependency-name: "github.com/mattn/go-colorable"
      - dependency-name: "github.com/mstoykov/k6-taskqueue-lib"
      - dependency-name: "github.com/stretchr/testify"
      - dependency-name: "go.opentelemetry.io/otel"
      - dependency-name: "go.opentelemetry.io/otel/exporters/otlp/otlptrace"
      - dependency-name: "go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"
      - dependency-name: "go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp"
      - dependency-name: "go.opentelemetry.io/otel/sdk"
      - dependency-name: "go.opentelemetry.io/otel/trace"
