name: "Auto assign maintainer to issue"
on:
  # makes this workflow re-usable
  workflow_call:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  assign-user:
    runs-on: ubuntu-latest
    # issue_comment triggers for both, issues and prs,
    # as we need to run only on issues, it filter out prs.
    if: ${{ !github.event.issue.pull_request }}
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const assignees = ['codebien', 'inancgumus', 'joanlopez', 'mstoykov', 'olegbespalov', 'oleiade'];
            const assigneeCount = 1;

            // Do not automatically assign users if someone was already assigned or it was opened by a maintainer
            if (context.payload.issue.assignees.length > 0 || assignees.includes(context.actor)) {
              return;
            }
            const crypto = require("node:crypto");

            const getNRandom = (n, array) => {
              let result = new Array();
              for (;n > 0 && array.length > 0; n--) {
                const chosen = array[crypto.randomInt(array.length)];
                result.push(chosen);
                array = array.filter(el => el != chosen);
              }
              return result;
            }

            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: getNRandom(assigneeCount, assignees),
            });
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ["triage"]
            });
